version: '3.8'
services:
  db:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword

  db2:
    image: postgres:13
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5434:5432
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
