FROM ubuntu:latest
LABEL authors="emin"

# Не хватает copy source destination для добавления скомпилированного джарника в докер-образ
# Установка переменных среды
# ENV MY_ENV=VALUE \
#     MY_ENV_2=VALUE2

ENTRYPOINT ["top", "-b"]